name: Publish Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[skip ci')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io --username nycodeghg --password-stdin
      - name: Build & Tag
        run: docker build -t ghcr.io/nycodeghg/wiki/wiki:latest -t ghcr.io/nycodeghg/wiki/wiki:"$GITHUB_SHA" .
      - name: Push
        run: docker push ghcr.io/nycodeghg/wiki/wiki:latest
      - name: Push specific tag
        run: docker push ghcr.io/nycodeghg/wiki/wiki:"$GITHUB_SHA"