name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go 1.16.4
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - name: Build with Go
        run: go build .